use_frameworks!

target 'VegaScrollFlowLayout_Example' do
  pod 'VegaScrollFlowLayout', :path => 'https://github.com/AppliKeySolutions/VegaScroll.git'

  target 'VegaScrollFlowLayout_Tests' do
    inherit! :search_paths

    
  end
end
